services:
  app:
    container_name: devcontainer-bashscript-app
    image: ubuntu:24.04
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.01"
          memory: 256M
    command: sleep infinity
    restart: unless-stopped
